# Enabling the metrics server proxy
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true
# Enabling the HostPath Mapper (to show internal logging)
hostpathMapper:
  enabled: true
# Node Syncing Modes
sync:
  nodes:
    enabled: true
    syncAllNodes: true

# Map Host Cluster Service to vCluster Service https://www.vcluster.com/docs/networking/internal_traffic/host_to_vcluster
# mapServices:
#   fromHost:
#     - from: config-vcluster-development/development
#       to: monitoring/prometheus-operated.monitoring.svc:9090

# Map vCluster Service to Host Cluster Service
# mapServices:
#  fromVirtual:
#  - from: my-virtual-namespace/my-virtual-service
#    to: my-host-service

# adjust isolation settings through helm values.
isolation:
  enabled: true

  podSecurityStandard: baseline

# Resource Quotas
#  resourceQuota:
#    enabled: true
#    quota:
#      requests.cpu: 4
#      requests.memory: 4Gi
#      requests.storage: "50Gi"
#      requests.ephemeral-storage: 50Gi
#      limits.memory: 4Gi
#      limits.ephemeral-storage: 60Gi
#      services.nodeports: 10
#      services.loadbalancers: 2
#      count/endpoints: 20
#      count/pods: 20
#      count/services: 20
#      count/secrets: 100
#      count/configmaps: 100
#      count/persistentvolumeclaims: 20
  networkPolicy:
    enabled: true


#networkPolicy:
#  enabled: true
#  allowIngressFrom: []
#  allowEgressTo: []
  # allowIngressFrom: []
  # allowEgressTo:
  #   - namespaceSelector:
  #       matchLabels:
  #         app: config-vcluster-development
  #   - namespaceSelector:
  #       matchLabels:
  #         app: config-vcluster-production
