apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-sa-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-sa-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: admin-sa
  namespace: staging
roleRef:
  kind: ClusterRole
  name: admin-sa-cluster-role
  apiGroup: rbac.authorization.k8s.io
  #
