apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <username>-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <username>-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: <username>
roleRef:
  kind: ClusterRole
  name: <serv-acc>-cluster-role
  namespace: <namespace>
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <username>-cluster-role
  namespace: <namespace>
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <username>-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: <serv-acc>
roleRef:
  kind: Role
  name: <username>-cluster-role
  namespace: <namespace>
  apiGroup: rbac.authorization.k8s.io

#  Admin-user auf ADMIN