apiVersion: v1
kind: Service
metadata:
  labels:
    app: vcluster
  name: admin-prom-svc
  namespace: vcluster-administration
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: syncer
    port: 6444
    protocol: TCP
    targetPort: 6444
  selector:
    app: vcluster
    release: administration
  sessionAffinity: None
  type: ClusterIP