apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-prod-sa-production-k3d-main-cluster-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-prod-sa-production-k3d-main-cluster-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: admin-prod-sa-production-k3d-main-cluster
  namespace: production
roleRef:
  kind: ClusterRole
  name: admin-prod-sa-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-prod-sa-production-k3d-main-cluster-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-prod-sa-production-k3d-main-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: admin-prod-sa
  namespace: production
roleRef:
  kind: Role
  name: admin-prod-sa-production-k3d-main-cluster-role
  apiGroup: rbac.authorization.k8s.io

#  Admin-user auf ADMIN