apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-dev-sa-development-k3d-main-cluster-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-dev-sa-development-k3d-main-cluster-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: dev-dev-sa-development-k3d-main-cluster
  namespace: development
roleRef:
  kind: ClusterRole
  name: dev-dev-sa-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-dev-sa-development-k3d-main-cluster-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-dev-sa-development-k3d-main-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: dev-dev-sa
  namespace: development
roleRef:
  kind: Role
  name: dev-dev-sa-development-k3d-main-cluster-role
  apiGroup: rbac.authorization.k8s.io

  #  dev-user auf DEV