apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <username>-cluster-access-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <username>-cluster-access-rolebinding
subjects:
- kind: User
  name: <username>-cluster
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: <username>-cluster-access-role
  apiGroup: rbac.authorization.k8s.io
